services:
  tangent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/${COMPOSE_PROJECT_NAME:-tangent-llc/tangent-template}-devcontainer:latest
    ports:
      - '3000:3000'
    volumes:
      - ..:/workspaces/${COMPOSE_PROJECT_NAME:-tangent}:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
